//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C____ANS005
    {
        public long ID { get; set; }
        public long ANSXXX005_ID { get; set; }
        public long CARD_ID { get; set; }
        public short PARTNER_ID { get; set; }
        public string CARDNO { get; set; }
        public Nullable<long> PARTNER_CARD_ID { get; set; }
        public Nullable<decimal> TRANSACTION_LIMIT_CARDACCOUNT { get; set; }
        public Nullable<decimal> DAILY_LIMIT_CARDACCOUNT { get; set; }
        public Nullable<decimal> TRANSACTION_LIMIT_ACCOUNT { get; set; }
        public Nullable<decimal> DAILY_LIMIT_ACCOUNT { get; set; }
        public int STATUS { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE_PRODUCT { get; set; }
        public Nullable<int> ACCOUNT_TYPE_ID { get; set; }
        public int ACCOUNT_TYPE_ID_STATUS { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE_ACCOUNT { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE_CARD { get; set; }
        public Nullable<decimal> CURRENT_BALANCE { get; set; }
    }
}
