//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C____TEMP002
    {
        public long id { get; set; }
        public Nullable<long> request_id { get; set; }
        public string partner_request_id { get; set; }
        public Nullable<int> partner_id { get; set; }
        public Nullable<short> card_type_id { get; set; }
        public string carrier_type_id { get; set; }
        public string envelope_type_id { get; set; }
        public string plastic_type_id { get; set; }
        public string attachement_id { get; set; }
        public string package_attachement_id { get; set; }
        public string delivery_list_id { get; set; }
        public Nullable<int> card_count { get; set; }
        public Nullable<System.DateTime> valid_to { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> creation_datetime { get; set; }
        public Nullable<byte> request_status { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
    }
}
