//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C___PARTNER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C___PARTNER()
        {
            this.C___CARD = new HashSet<C___CARD>();
            this.C___CONSTANT_PARTNER = new HashSet<C___CONSTANT_PARTNER>();
        }
    
        public int id { get; set; }
        public byte partner_type_id { get; set; }
        public string code { get; set; }
        public string organization_name { get; set; }
        public System.DateTime creation_datetime { get; set; }
        public int integrity_constant { get; set; }
        public Nullable<int> rw_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C___CARD> C___CARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C___CONSTANT_PARTNER> C___CONSTANT_PARTNER { get; set; }
        public virtual C___PARTNER_TYPE C___PARTNER_TYPE { get; set; }
    }
}
