//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C____REQ009
    {
        public long id { get; set; }
        public int partner_id { get; set; }
        public long card_order_request_id { get; set; }
        public System.DateTime insert_datetime { get; set; }
        public Nullable<long> request_id { get; set; }
    }
}
