//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C___APPLICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C___APPLICATION()
        {
            this.C___NOTIFICATION = new HashSet<C___NOTIFICATION>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SHORTNAME { get; set; }
        public bool BY_PARTNER { get; set; }
        public Nullable<int> PARTNER_ID { get; set; }
        public bool STATUS { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public bool IS_PERIODICALLY_EXECUTED { get; set; }
        public Nullable<int> TIME_INTERVAL { get; set; }
        public Nullable<int> TOLERANCE_PERIOD { get; set; }
        public System.DateTime INSERTED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C___NOTIFICATION> C___NOTIFICATION { get; set; }
    }
}
