//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C____ANS002
    {
        public long id { get; set; }
        public Nullable<int> partner_id { get; set; }
        public Nullable<long> answer_id { get; set; }
        public Nullable<long> request_id { get; set; }
        public System.DateTime insert_time { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public Nullable<byte> request_status { get; set; }
        public string message { get; set; }
        public string additional_column1 { get; set; }
    }
}
