//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C____REQ001
    {
        public long id { get; set; }
        public Nullable<int> partner_id { get; set; }
        public Nullable<long> request_id { get; set; }
        public Nullable<long> partner_request_id { get; set; }
        public Nullable<int> terminal_type_id { get; set; }
        public string external_terminal_id { get; set; }
        public Nullable<bool> new_accept_state { get; set; }
        public Nullable<System.DateTime> creation_datetime { get; set; }
        public Nullable<bool> flag { get; set; }
        public Nullable<System.DateTime> answer_datetime { get; set; }
        public Nullable<bool> request_status { get; set; }
        public int ACCOUNT_TYPE_ID { get; set; }
    }
}
