//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C___CARD
    {
        public long id { get; set; }
        public int partner_id { get; set; }
        public long partner_card_id { get; set; }
        public System.DateTime batch_time { get; set; }
        public Nullable<byte> status { get; set; }
    
        public virtual C___PARTNER C___PARTNER { get; set; }
    }
}
