//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C___EXPORT_MAP
    {
        public long ID { get; set; }
        public string CONSTANT_NAME { get; set; }
        public string CONSTANT_VALUE { get; set; }
        public string CONSTANT_DESCRIPTION { get; set; }
        public string TEMPLATE_FILE_NAME { get; set; }
        public string ADDITIONAL_COLUMN1 { get; set; }
        public string ADDITIONAL_COLUMN2 { get; set; }
        public System.DateTime INSERTDATETIME { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATETIME { get; set; }
    }
}
