//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C____ANS008
    {
        public long ID { get; set; }
        public Nullable<int> PARTNER_ID { get; set; }
        public Nullable<long> ANS_ID { get; set; }
        public Nullable<long> REQUEST_ID { get; set; }
        public Nullable<byte> REQUEST_STATUS { get; set; }
        public string REQUEST_MESSAGE { get; set; }
        public Nullable<long> AUTHORIZATION_ID_FROM_CARD { get; set; }
        public Nullable<long> AUTHORIZATION_ID_TO_CARD { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> CHANGE_TIME { get; set; }
        public Nullable<decimal> CURRENT_BALANCE_FROM_CARD { get; set; }
        public Nullable<decimal> CURRENT_BALANCE_TO_CARD { get; set; }
    }
}
