//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C____ANS007
    {
        public string TERMINALID { get; set; }
        public string EXTERNALTERMINALID { get; set; }
        public short PARTNER_ID { get; set; }
        public int STATUS { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> ACCOUNT_TYPE_ID { get; set; }
    }
}
