//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C____ANS006
    {
        public long TRANSACTION_ID { get; set; }
        public long CARD_ID { get; set; }
        public short PARTNER_ID { get; set; }
        public Nullable<short> OPERATIONAL_CODE { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime TRANSACTION_DATE { get; set; }
        public Nullable<System.DateTime> ORG_TRANSACTION_DATE { get; set; }
        public decimal PREPAID_BALANCE { get; set; }
        public string TERMINAL_ID { get; set; }
        public string RESPONSE_CODE { get; set; }
        public string INTERNAL_ERROR_MESSAGE { get; set; }
        public Nullable<decimal> REMAINING_DAILY_LIMIT { get; set; }
        public string MTI { get; set; }
        public string ORG_REQUEST_MTI { get; set; }
        public string STAN { get; set; }
        public string ORG_STAN { get; set; }
        public string AUTHCODE { get; set; }
        public Nullable<int> ACCOUNT_TYPE_ID { get; set; }
    }
}
