//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C___HOLIDAY
    {
        public int id { get; set; }
        public byte month { get; set; }
        public byte day { get; set; }
        public string description { get; set; }
        public System.DateTime insertdatetime { get; set; }
        public Nullable<System.DateTime> lastupdatedatetime { get; set; }
        public string country { get; set; }
    }
}
