//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C____ANS004
    {
        public long id { get; set; }
        public Nullable<int> partner_id { get; set; }
        public Nullable<long> ans_id { get; set; }
        public Nullable<long> request_id { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public Nullable<bool> request_status { get; set; }
        public string request_message { get; set; }
        public Nullable<int> card_status_code { get; set; }
    }
}
