//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALLERINFORMATION
    {
        public long CALLER_ID { get; set; }
        public long CALL_ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public string POSTCODE { get; set; }
        public string ADDRESS { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
    
        public virtual CALLCENTER CALLCENTER { get; set; }
        public virtual CITY CITY { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual COUNTY COUNTY { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
