//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALLRECORD
    {
        public long CALLRECORD_ID { get; set; }
        public long CALL_ID { get; set; }
        public string MESSAGE { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
    
        public virtual CALLCENTER CALLCENTER { get; set; }
        public virtual USER USER { get; set; }
    }
}
