//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALLCENTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CALLCENTER()
        {
            this.CALLERINFORMATION = new HashSet<CALLERINFORMATION>();
            this.CALLRECORD = new HashSet<CALLRECORD>();
        }
    
        public long CALL_ID { get; set; }
        public short ORGANIZATION_ID { get; set; }
        public int OBJECTTYPE_ID { get; set; }
        public int CALLCATEGORY_ID { get; set; }
        public int CALLREASON_ID { get; set; }
        public int CALLCHANNEL_ID { get; set; }
        public int CALLIMPORTANCE_ID { get; set; }
        public string SUBJECT { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
        public int CALLRESULT_ID { get; set; }
        public int CALLSTATUS_ID { get; set; }
    
        public virtual CONSTANT CONSTANT { get; set; }
        public virtual CONSTANT CONSTANT1 { get; set; }
        public virtual CONSTANT CONSTANT2 { get; set; }
        public virtual CONSTANT CONSTANT3 { get; set; }
        public virtual CONSTANT CONSTANT4 { get; set; }
        public virtual CONSTANT CONSTANT5 { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual CONSTANT CONSTANT6 { get; set; }
        public virtual ORGANIZATION ORGANIZATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALLERINFORMATION> CALLERINFORMATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALLRECORD> CALLRECORD { get; set; }
    }
}
