//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGNCRITERION
    {
        public int CAMPAIGNCRITERION_ID { get; set; }
        public int CAMPAIGN_ID { get; set; }
        public short CRITERIONOBJECT_TYPE_ID { get; set; }
        public int CRITERIONOBJECT_ID { get; set; }
        public Nullable<int> SCOPE { get; set; }
    }
}
