//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGNBLACKLIST
    {
        public int CAMPAIGNBLACKLIST_ID { get; set; }
        public Nullable<int> CAMPAIGN_ID { get; set; }
        public long CARD_ID { get; set; }
        public string CARDNO { get; set; }
    
        public virtual CAMPAIGN CAMPAIGN { get; set; }
        public virtual CARD CARD { get; set; }
    }
}
