//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGNPOINT
    {
        public int CAMPAIGNPOINT_ID { get; set; }
        public int CAMPAIGN_ID { get; set; }
        public decimal MINPOINT { get; set; }
        public decimal MAXPOINT { get; set; }
        public decimal POINTRATE { get; set; }
        public decimal CONSTANTPOINT { get; set; }
        public Nullable<decimal> MINDISCOUNT { get; set; }
        public Nullable<decimal> MAXDISCOUNT { get; set; }
        public Nullable<decimal> MINFLATPOINTS { get; set; }
        public Nullable<decimal> MAXFLATPOINTS { get; set; }
        public Nullable<decimal> MINFLATDISCOUNT { get; set; }
        public Nullable<decimal> MAXFLATDISCOUNT { get; set; }
        public Nullable<int> BREAKPOINTTYPE { get; set; }
        public string GIFTSELECTED { get; set; }
        public Nullable<decimal> PAYMENTREQUIREMENTFORGIFT { get; set; }
    
        public virtual CAMPAIGN CAMPAIGN { get; set; }
    }
}
