//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGNRFM
    {
        public int CAMPAIGNRFM_ID { get; set; }
        public int CAMPAIGN_ID { get; set; }
        public short RFMTYPE { get; set; }
        public int MAXWIN { get; set; }
        public short WINTYPE { get; set; }
        public decimal WINPOINT { get; set; }
        public int GIFT_ID { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public string MESSAGE { get; set; }
        public decimal TARGETVALUE { get; set; }
        public int BONUSPERIODDAY { get; set; }
    
        public virtual CAMPAIGN CAMPAIGN { get; set; }
    }
}
