//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGNLIMIT
    {
        public int CAMPAIGNLIMIT_ID { get; set; }
        public int CAMPAIGN_ID { get; set; }
        public int LIMITTYPE { get; set; }
        public int MINLIMIT { get; set; }
        public int MAXLIMIT { get; set; }
        public Nullable<System.TimeSpan> MONDAYSTARTTIME { get; set; }
        public Nullable<System.TimeSpan> MONDAYENDTIME { get; set; }
        public Nullable<System.TimeSpan> TUESDAYSTARTTIME { get; set; }
        public Nullable<System.TimeSpan> TUESDAYENDTIME { get; set; }
        public Nullable<System.TimeSpan> WEDNESDAYSTARTTIME { get; set; }
        public Nullable<System.TimeSpan> WEDNESDAYENDTIME { get; set; }
        public Nullable<System.TimeSpan> THURSDAYSTARTTIME { get; set; }
        public Nullable<System.TimeSpan> THURSDAYENDTIME { get; set; }
        public Nullable<System.TimeSpan> FRIDAYSTARTTIME { get; set; }
        public Nullable<System.TimeSpan> FRIDAYENDTIME { get; set; }
        public Nullable<System.TimeSpan> SATURDAYSTARTTIME { get; set; }
        public Nullable<System.TimeSpan> SATURDAYENDTIME { get; set; }
        public Nullable<System.TimeSpan> SUNDAYSTARTTIME { get; set; }
        public Nullable<System.TimeSpan> SUNDAYENDTIME { get; set; }
        public string ACTIVEDAYTIME { get; set; }
    
        public virtual CAMPAIGN CAMPAIGN { get; set; }
    }
}
