//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGNHISTORY
    {
        public long CAMPAIGNHISTORY_ID { get; set; }
        public Nullable<int> CAMPAIGN_ID { get; set; }
        public long CUSTOMER_ID { get; set; }
        public int MERCHANT_ID { get; set; }
        public int GIFTCOUNT { get; set; }
        public int GIFT_ID { get; set; }
        public decimal BONUS { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<System.DateTime> WINDATE { get; set; }
        public Nullable<long> TRANSACTION_ID { get; set; }
        public Nullable<long> GIFTORDER_ID { get; set; }
        public Nullable<System.DateTime> LASTORDERDATE { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public Nullable<int> CAMPAIGNOWNERTYPE { get; set; }
        public decimal TXBONUS { get; set; }
        public long TXAMOUNT { get; set; }
        public int TXCOUNT { get; set; }
    
        public virtual CAMPAIGN CAMPAIGN { get; set; }
        public virtual CAMPAIGNHISTORY CAMPAIGNHISTORY1 { get; set; }
        public virtual CAMPAIGNHISTORY CAMPAIGNHISTORY2 { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
