//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGNMESSAGE
    {
        public int CAMPAIGNMESSAGE_ID { get; set; }
        public int CAMPAIGN_ID { get; set; }
        public int MESSAGETYPE_ID { get; set; }
        public int DELIVERYMETHOD_ID { get; set; }
        public string MESSAGE { get; set; }
    
        public virtual CAMPAIGN CAMPAIGN { get; set; }
        public virtual CONSTANT CONSTANT { get; set; }
    }
}
