//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGNCUSTOMER
    {
        public int CAMPAIGNCUSTOMER_ID { get; set; }
        public int CAMPAIGN_ID { get; set; }
        public Nullable<int> GENDER { get; set; }
        public Nullable<int> MINIMUMAGE { get; set; }
        public Nullable<int> MAXIMUMAGE { get; set; }
        public Nullable<int> MEMBERYEAR { get; set; }
        public Nullable<int> FORCHILDREN { get; set; }
        public Nullable<bool> BIRTHDAY { get; set; }
    
        public virtual CAMPAIGN CAMPAIGN { get; set; }
        public virtual CONSTANT CONSTANT { get; set; }
    }
}
