//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD_PIN_STATUS
    {
        public int CARD_PIN_STATUS_ID { get; set; }
        public Nullable<long> CARD_ID { get; set; }
        public Nullable<int> PIN_TRY_COUNT { get; set; }
        public System.DateTime WRONG_PIN_DATE { get; set; }
    }
}
