//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDPOOLDETAIL
    {
        public long CARDPOOLDETAIL_ID { get; set; }
        public long CARDPOOL_ID { get; set; }
        public string CARDNO { get; set; }
        public string CARDNO_MASK { get; set; }
        public string CARDNO_HASH { get; set; }
        public byte[] CARDNO_ENCRYPTED { get; set; }
        public short STATUS { get; set; }
    
        public virtual CARDPOOL CARDPOOL { get; set; }
    }
}
