//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDPRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARDPRODUCT()
        {
            this.CARD = new HashSet<CARD>();
            this.CARD_TRANSFER = new HashSet<CARD_TRANSFER>();
            this.CARDPOOL = new HashSet<CARDPOOL>();
            this.MERCHANT_CARDTYPE_PERMISSION = new HashSet<MERCHANT_CARDTYPE_PERMISSION>();
        }
    
        public short CARDPRODUCT_ID { get; set; }
        public short ORGANIZATION_ID { get; set; }
        public int ENIGMA_MAIN_KEY_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string BIN { get; set; }
        public string CARDPRODUCT_CODE_START { get; set; }
        public string CARDPRODUCT_CODE_END { get; set; }
        public long SEQNO { get; set; }
        public string SERVICE_CODE { get; set; }
        public int BONUSACTIVE { get; set; }
        public int PREPAIDACTIVE { get; set; }
        public int ANONYMOUSCARD { get; set; }
        public int CARD_ACTIVATION { get; set; }
        public int BONUSRATE_TYPE { get; set; }
        public decimal BONUSRATE { get; set; }
        public short ALLOWABLE_PIN_TRY_COUNT { get; set; }
        public Nullable<int> ALLOWABLE_ATC_DIFFERENCE_LIMIT { get; set; }
        public decimal TRANSACTION_LIMIT { get; set; }
        public decimal DAILY_LIMIT { get; set; }
        public Nullable<decimal> NEXT_DAILY_LIMIT { get; set; }
        public int ACQUIRER_ID { get; set; }
        public Nullable<int> ISSUER_ID { get; set; }
        public Nullable<decimal> PANLENGTH { get; set; }
        public string ALLOWPAYMENT { get; set; }
        public string RESERVED { get; set; }
        public Nullable<decimal> MERCHANT_CONTRIBUTION { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
        public int STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARD> CARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARD_TRANSFER> CARD_TRANSFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARDPOOL> CARDPOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MERCHANT_CARDTYPE_PERMISSION> MERCHANT_CARDTYPE_PERMISSION { get; set; }
    }
}
