//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD_EXTRA
    {
        public long CARD_EXTRA_ID { get; set; }
        public long CARD_ID { get; set; }
        public string APPLICATION { get; set; }
        public string ATC { get; set; }
    
        public virtual CARD CARD { get; set; }
    }
}
