//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTINFO
    {
        public long CONTACTINFO_ID { get; set; }
        public int CONTACTINFOTYPE_ID { get; set; }
        public int OBJECTTYPE_ID { get; set; }
        public long OBJECT_ID { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS2 { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public string POSTCODE { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string WEB { get; set; }
        public string TAXOFFICE { get; set; }
        public string TAXNUMBER { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string ALTERNAMEEMAIL { get; set; }
        public string ALTERNATEPHONE { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public Nullable<int> INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
        public int STATUS { get; set; }
    }
}
