//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORPORATECUSTOMERCONTRACT
    {
        public int CORPORATECUSTOMERCONTRACT_ID { get; set; }
        public int CORPORATECUSTOMER_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> CONTRACTTYPE_ID { get; set; }
        public string FILEURL { get; set; }
        public Nullable<System.DateTime> CONTRACTSTARTDATE { get; set; }
        public Nullable<System.DateTime> CONTRACTFINISHDATE { get; set; }
        public Nullable<decimal> DISCOUNT_RATE { get; set; }
        public Nullable<short> VALOR_DAY_COUNT { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public int STATUS { get; set; }
    }
}
