//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COUNTY()
        {
            this.CALLERINFORMATION = new HashSet<CALLERINFORMATION>();
        }
    
        public int COUNTY_ID { get; set; }
        public int CITY_ID { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public Nullable<short> DISPLAYORDER { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALLERINFORMATION> CALLERINFORMATION { get; set; }
    }
}
