//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERPRIVATECHILDINFO
    {
        public int CUSTOMERPRIVATECHILDINFO_ID { get; set; }
        public long CUSTOMER_ID { get; set; }
        public string CHILDNAME { get; set; }
        public int CHILDGENDER { get; set; }
        public Nullable<System.DateTime> CHILDBIRTHDATE { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public Nullable<int> INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
    
        public virtual CONSTANT CONSTANT { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
