//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERPRIVATEINFO
    {
        public long CUSTOMERPRIVATEINFO_ID { get; set; }
        public long CUSTOMER_ID { get; set; }
        public Nullable<int> MARITIALSTATUS { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string BIRTHPLACE { get; set; }
        public Nullable<int> NATIONALITY { get; set; }
        public Nullable<int> BIRTHCITY { get; set; }
        public Nullable<int> MUNICIPALITY { get; set; }
        public string SPOUSENAME { get; set; }
        public Nullable<System.DateTime> SPOUSEBIRTHDATE { get; set; }
        public Nullable<int> SPOUSEPROFESSION { get; set; }
        public Nullable<System.DateTime> MARRIAGEANNIVERSARY { get; set; }
        public string IDENTITYNUMBER { get; set; }
        public Nullable<int> IDENTIFICATIONTYPE { get; set; }
        public Nullable<int> EMPLOYERCLASS { get; set; }
        public Nullable<int> EDUCATION { get; set; }
        public Nullable<int> PROFESSION { get; set; }
        public string EMPLOYERNAME { get; set; }
        public Nullable<decimal> INCOME { get; set; }
        public Nullable<int> JOBPOSITION { get; set; }
        public string FATHERFIRSTNAME { get; set; }
        public string FATHERLASTNAME { get; set; }
        public string MOTHERNAME { get; set; }
        public string MOTHERMAIDENLASTNAME { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
    }
}
