//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCIALINFO
    {
        public long CARD_ID { get; set; }
        public decimal NETBONUS { get; set; }
        public decimal TOTALAWARDBONUS { get; set; }
        public decimal TOTALREDEEMBONUS { get; set; }
        public decimal NETBALANCE { get; set; }
        public decimal TOTALLOADBALANCE { get; set; }
        public decimal TOTALREDEEMBALANCE { get; set; }
        public int TOTALCOUNT { get; set; }
        public Nullable<System.DateTime> LASTTXDATE { get; set; }
    
        public virtual CARD CARD { get; set; }
    }
}
