//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIZEDPROPERTY
    {
        public int LOCALIZEDPROPERTY_ID { get; set; }
        public int ENTITY_ID { get; set; }
        public short LANGUAGE_ID { get; set; }
        public string LOCALEKEYGROUP { get; set; }
        public string LOCALEKEY { get; set; }
        public string LOCALEVALUE { get; set; }
    }
}
