//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALSTRINGRESOURCE
    {
        public int LOCALSTRINGRESOURCE_ID { get; set; }
        public short LANGUAGE_ID { get; set; }
        public string RESOURCENAME { get; set; }
        public string RESOURCEVALUE { get; set; }
    }
}
