//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCHANT_CATEGORY_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MERCHANT_CATEGORY_GROUP()
        {
            this.MERCHANT_CATEGORY_CODE = new HashSet<MERCHANT_CATEGORY_CODE>();
        }
    
        public int MCC_GROUP_ID { get; set; }
        public string MCC_GROUP_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MERCHANT_CATEGORY_CODE> MERCHANT_CATEGORY_CODE { get; set; }
    }
}
