//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCHANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MERCHANT()
        {
            this.MERCHANT_BALANCE_PERIOD = new HashSet<MERCHANT_BALANCE_PERIOD>();
            this.MERCHANT_CARDTYPE_PERMISSION = new HashSet<MERCHANT_CARDTYPE_PERMISSION>();
        }
    
        public int MERCHANT_ID { get; set; }
        public short ORGANIZATION_ID { get; set; }
        public int MERCHANTTYPE_ID { get; set; }
        public Nullable<int> MERCHANT_GROUP_ID { get; set; }
        public string CATEGORYCODE { get; set; }
        public string NAME { get; set; }
        public string MERCHANTCODE { get; set; }
        public System.DateTime AGREEMENTDATE { get; set; }
        public System.TimeSpan STOREOPENINGTIME { get; set; }
        public System.TimeSpan STORECLOSINGTIME { get; set; }
        public int CONTACTMETHOD { get; set; }
        public string TAX_NAME { get; set; }
        public string TAX_NO { get; set; }
        public Nullable<decimal> COMMISSION_RATE { get; set; }
        public Nullable<int> BALANCE_PAYMENTPLAN_TYPE_ID { get; set; }
        public Nullable<short> DAY { get; set; }
        public string CURRENCY_CODE { get; set; }
        public bool ISWEBMERCHANT { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
        public int STATUS { get; set; }
    
        public virtual CONSTANT CONSTANT { get; set; }
        public virtual CONSTANT CONSTANT1 { get; set; }
        public virtual CONSTANT CONSTANT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MERCHANT_BALANCE_PERIOD> MERCHANT_BALANCE_PERIOD { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual ORGANIZATION ORGANIZATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MERCHANT_CARDTYPE_PERMISSION> MERCHANT_CARDTYPE_PERMISSION { get; set; }
    }
}
