//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCHANT_CARDTYPE_PERMISSION
    {
        public long MERCHANT_CARDTYPE_PERMISSION_ID { get; set; }
        public int MERCHANT_ID { get; set; }
        public short CARDPRODUCT_ID { get; set; }
        public int BONUSRATE_TYPE { get; set; }
        public decimal ADDITIONALBONUSRATE { get; set; }
        public int COLLECTBONUSACTIVE { get; set; }
        public int REDEEMBONUSACTIVE { get; set; }
        public int USEPREPAIDACTIVE { get; set; }
        public int LOADPREPAIDACTIVE { get; set; }
        public int REFUND { get; set; }
        public int CANCELATTION { get; set; }
        public int CAMPAIGN_ACTIVE { get; set; }
        public Nullable<short> BONUS_EXPIRATION_DAY { get; set; }
        public Nullable<decimal> MERCHANT_CONTRIBUTION { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
        public int STATUS { get; set; }
    
        public virtual CARDPRODUCT CARDPRODUCT { get; set; }
        public virtual CONSTANT CONSTANT { get; set; }
        public virtual CONSTANT CONSTANT1 { get; set; }
        public virtual CONSTANT CONSTANT2 { get; set; }
        public virtual CONSTANT CONSTANT3 { get; set; }
        public virtual CONSTANT CONSTANT4 { get; set; }
        public virtual CONSTANT CONSTANT5 { get; set; }
        public virtual CONSTANT CONSTANT6 { get; set; }
        public virtual MERCHANT MERCHANT { get; set; }
        public virtual USER USER { get; set; }
    }
}
