//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCHANT_CATEGORY_CODE
    {
        public string CATEGORYCODE { get; set; }
        public Nullable<int> MERCHANT_CATEGORY_GROUP_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual MERCHANT_CATEGORY_GROUP MERCHANT_CATEGORY_GROUP { get; set; }
    }
}
