//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCHANT_BALANCE_PERIOD
    {
        public int REFNO { get; set; }
        public short ORGANIZATION_ID { get; set; }
        public int MERCHANT_ID { get; set; }
        public System.DateTime BALANCE_DATE { get; set; }
        public bool CLOSED { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool ACTIVE { get; set; }
    
        public virtual MERCHANT MERCHANT { get; set; }
        public virtual ORGANIZATION ORGANIZATION { get; set; }
    }
}
