//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORGANIZATION()
        {
            this.CALLCENTER = new HashSet<CALLCENTER>();
            this.CAMPAIGN = new HashSet<CAMPAIGN>();
            this.CARD = new HashSet<CARD>();
            this.CARD_TRANSFER = new HashSet<CARD_TRANSFER>();
            this.CARDPOOL = new HashSet<CARDPOOL>();
            this.CUSTOMER = new HashSet<CUSTOMER>();
            this.MERCHANT = new HashSet<MERCHANT>();
            this.MERCHANT_BALANCE_PERIOD = new HashSet<MERCHANT_BALANCE_PERIOD>();
            this.SECURITYPOLICY = new HashSet<SECURITYPOLICY>();
            this.USER_ORGANIZATION_MAP = new HashSet<USER_ORGANIZATION_MAP>();
            this.USERTEMPLATE = new HashSet<USERTEMPLATE>();
        }
    
        public short ORGANIZATION_ID { get; set; }
        public int ORGANIZATIONTYPE_ID { get; set; }
        public Nullable<int> HOLDING_ID { get; set; }
        public string NAME { get; set; }
        public string LONG_NAME { get; set; }
        public string CODE { get; set; }
        public Nullable<short> LEVEL { get; set; }
        public byte[] IMAGE_PATH { get; set; }
        public string POS_LOGO_PATH { get; set; }
        public string CONVERTED_POS_LOGO_PATH { get; set; }
        public string POS_DISPLAYLOGO_PATH { get; set; }
        public string CONVERTED_POS_DISPLAYLOGO_PATH { get; set; }
        public int INSERTUSER_ID { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
        public int STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALLCENTER> CALLCENTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPAIGN> CAMPAIGN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARD> CARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARD_TRANSFER> CARD_TRANSFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARDPOOL> CARDPOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER> CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MERCHANT> MERCHANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MERCHANT_BALANCE_PERIOD> MERCHANT_BALANCE_PERIOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYPOLICY> SECURITYPOLICY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_ORGANIZATION_MAP> USER_ORGANIZATION_MAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEMPLATE> USERTEMPLATE { get; set; }
    }
}
