//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAGE()
        {
            this.USERTEMPLATE_PAGE_MAP = new HashSet<USERTEMPLATE_PAGE_MAP>();
        }
    
        public short PAGE_ID { get; set; }
        public short PARENT_ID { get; set; }
        public string NAME { get; set; }
        public string AREA_NAME { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string ACTION_NAME { get; set; }
        public string ACTION_ID { get; set; }
        public short ORDER_NO { get; set; }
        public Nullable<int> PARENT_ORDER_BY { get; set; }
        public bool SHOW_ON_MENU { get; set; }
        public string ICON_URL { get; set; }
        public string RESOURCENAME { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
        public int STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEMPLATE_PAGE_MAP> USERTEMPLATE_PAGE_MAP { get; set; }
    }
}
