//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTAG
    {
        public string TAG { get; set; }
        public short LENGTH { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string TXLOGCOLUMN { get; set; }
        public System.DateTime INSERTDATE { get; set; }
    }
}
