//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREFERENCEDATA
    {
        public int PREFERENCEDATA_ID { get; set; }
        public long CUSTOMER_ID { get; set; }
        public int PREFERENCEOPTION_ID { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public Nullable<int> INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
    }
}
