//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPONSE_CODES
    {
        public int RESPONSE_CODE_ID { get; set; }
        public string RESPONSE_CODE { get; set; }
        public string INTERNAL_RESPONSE_CODE { get; set; }
        public string INTERNAL_ERROR_MESSAGE { get; set; }
    }
}
