//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REWARDO_CARDNETEntities : DbContext
    {
        public REWARDO_CARDNETEntities()
            : base("name=REWARDO_CARDNETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CALLCENTER> CALLCENTER { get; set; }
        public virtual DbSet<CALLERINFORMATION> CALLERINFORMATION { get; set; }
        public virtual DbSet<CALLRECORD> CALLRECORD { get; set; }
        public virtual DbSet<CAMPAIGN> CAMPAIGN { get; set; }
        public virtual DbSet<CAMPAIGNBLACKLIST> CAMPAIGNBLACKLIST { get; set; }
        public virtual DbSet<CAMPAIGNCRITERION> CAMPAIGNCRITERION { get; set; }
        public virtual DbSet<CAMPAIGNCUSTOMER> CAMPAIGNCUSTOMER { get; set; }
        public virtual DbSet<CAMPAIGNHISTORY> CAMPAIGNHISTORY { get; set; }
        public virtual DbSet<CAMPAIGNLIMIT> CAMPAIGNLIMIT { get; set; }
        public virtual DbSet<CAMPAIGNMESSAGE> CAMPAIGNMESSAGE { get; set; }
        public virtual DbSet<CAMPAIGNPOINT> CAMPAIGNPOINT { get; set; }
        public virtual DbSet<CAMPAIGNRFM> CAMPAIGNRFM { get; set; }
        public virtual DbSet<CARD> CARD { get; set; }
        public virtual DbSet<CARD_EXTRA> CARD_EXTRA { get; set; }
        public virtual DbSet<CARD_PIN_STATUS> CARD_PIN_STATUS { get; set; }
        public virtual DbSet<CARD_TRANSFER> CARD_TRANSFER { get; set; }
        public virtual DbSet<CARDPOOL> CARDPOOL { get; set; }
        public virtual DbSet<CARDPOOLDETAIL> CARDPOOLDETAIL { get; set; }
        public virtual DbSet<CARDPRODUCT> CARDPRODUCT { get; set; }
        public virtual DbSet<CITY> CITY { get; set; }
        public virtual DbSet<CONSTANT> CONSTANT { get; set; }
        public virtual DbSet<CONTACTINFO> CONTACTINFO { get; set; }
        public virtual DbSet<CORPORATECUSTOMER> CORPORATECUSTOMER { get; set; }
        public virtual DbSet<CORPORATECUSTOMERCONTRACT> CORPORATECUSTOMERCONTRACT { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<COUNTY> COUNTY { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<CUSTOMERPRIVATECHILDINFO> CUSTOMERPRIVATECHILDINFO { get; set; }
        public virtual DbSet<CUSTOMERPRIVATEINFO> CUSTOMERPRIVATEINFO { get; set; }
        public virtual DbSet<FINANCIALINFO> FINANCIALINFO { get; set; }
        public virtual DbSet<LANGUAGE> LANGUAGE { get; set; }
        public virtual DbSet<LOCALIZEDPROPERTY> LOCALIZEDPROPERTY { get; set; }
        public virtual DbSet<LOCALSTRINGRESOURCE> LOCALSTRINGRESOURCE { get; set; }
        public virtual DbSet<MERCHANT> MERCHANT { get; set; }
        public virtual DbSet<MERCHANT_BALANCE_PERIOD> MERCHANT_BALANCE_PERIOD { get; set; }
        public virtual DbSet<MERCHANT_CARDTYPE_PERMISSION> MERCHANT_CARDTYPE_PERMISSION { get; set; }
        public virtual DbSet<MERCHANT_CATEGORY_CODE> MERCHANT_CATEGORY_CODE { get; set; }
        public virtual DbSet<MERCHANT_CATEGORY_GROUP> MERCHANT_CATEGORY_GROUP { get; set; }
        public virtual DbSet<ORGANIZATION> ORGANIZATION { get; set; }
        public virtual DbSet<PAGE> PAGE { get; set; }
        public virtual DbSet<PAGE_PERMISSION> PAGE_PERMISSION { get; set; }
        public virtual DbSet<POSERRORCODE> POSERRORCODE { get; set; }
        public virtual DbSet<POSTAG> POSTAG { get; set; }
        public virtual DbSet<PREFERENCEDATA> PREFERENCEDATA { get; set; }
        public virtual DbSet<PREFERENCEOPTION> PREFERENCEOPTION { get; set; }
        public virtual DbSet<RESPONSE_CODES> RESPONSE_CODES { get; set; }
        public virtual DbSet<SECURITYPOLICY> SECURITYPOLICY { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<USER_ORGANIZATION_MAP> USER_ORGANIZATION_MAP { get; set; }
        public virtual DbSet<USERTEMPLATE> USERTEMPLATE { get; set; }
        public virtual DbSet<USERTEMPLATE_PAGE_MAP> USERTEMPLATE_PAGE_MAP { get; set; }
    }
}
