//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITYPOLICY
    {
        public short SECURITYPOLICY_ID { get; set; }
        public short ORGANIZATION_ID { get; set; }
        public string SECURITYPOLICYTITLE { get; set; }
        public short PASSLENGTHMIN { get; set; }
        public short PASSCAPITALMIN { get; set; }
        public short PASSNUMBERMIN { get; set; }
        public short PASSSPECIALMIN { get; set; }
        public short PASSEXPIRYDAYS { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
        public int STATUS { get; set; }
    
        public virtual ORGANIZATION ORGANIZATION { get; set; }
    }
}
