//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ORGANIZATION_MAP
    {
        public int USER_ORGANIZATION_MAP_ID { get; set; }
        public int USER_ID { get; set; }
        public short ORGANIZATION_ID { get; set; }
    
        public virtual ORGANIZATION ORGANIZATION { get; set; }
        public virtual USER USER { get; set; }
    }
}
