//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CALLCENTER = new HashSet<CALLCENTER>();
            this.CALLCENTER1 = new HashSet<CALLCENTER>();
            this.CALLERINFORMATION = new HashSet<CALLERINFORMATION>();
            this.CALLERINFORMATION1 = new HashSet<CALLERINFORMATION>();
            this.CALLRECORD = new HashSet<CALLRECORD>();
            this.CAMPAIGN = new HashSet<CAMPAIGN>();
            this.CAMPAIGN1 = new HashSet<CAMPAIGN>();
            this.CARD_TRANSFER = new HashSet<CARD_TRANSFER>();
            this.CORPORATECUSTOMER = new HashSet<CORPORATECUSTOMER>();
            this.CORPORATECUSTOMER1 = new HashSet<CORPORATECUSTOMER>();
            this.CUSTOMERPRIVATECHILDINFO = new HashSet<CUSTOMERPRIVATECHILDINFO>();
            this.CUSTOMERPRIVATECHILDINFO1 = new HashSet<CUSTOMERPRIVATECHILDINFO>();
            this.MERCHANT = new HashSet<MERCHANT>();
            this.MERCHANT1 = new HashSet<MERCHANT>();
            this.MERCHANT_CARDTYPE_PERMISSION = new HashSet<MERCHANT_CARDTYPE_PERMISSION>();
            this.USERTEMPLATE = new HashSet<USERTEMPLATE>();
            this.USER_ORGANIZATION_MAP = new HashSet<USER_ORGANIZATION_MAP>();
            this.USERTEMPLATE1 = new HashSet<USERTEMPLATE>();
        }
    
        public int USER_ID { get; set; }
        public short USER_TEMPLATE_ID { get; set; }
        public short SECURITYPOLICY_ID { get; set; }
        public Nullable<int> USER_TYPE { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string MOBILE { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string RE_PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public short LANGUAGE_ID { get; set; }
        public Nullable<System.DateTime> LASTLOGINDATE { get; set; }
        public Nullable<System.DateTime> CHANGEPASSWORDDATE { get; set; }
        public System.DateTime INSERTDATE { get; set; }
        public int INSERTUSER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<int> LASTUPDATEUSER_ID { get; set; }
        public int STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALLCENTER> CALLCENTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALLCENTER> CALLCENTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALLERINFORMATION> CALLERINFORMATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALLERINFORMATION> CALLERINFORMATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALLRECORD> CALLRECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPAIGN> CAMPAIGN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPAIGN> CAMPAIGN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARD_TRANSFER> CARD_TRANSFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORPORATECUSTOMER> CORPORATECUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORPORATECUSTOMER> CORPORATECUSTOMER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERPRIVATECHILDINFO> CUSTOMERPRIVATECHILDINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERPRIVATECHILDINFO> CUSTOMERPRIVATECHILDINFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MERCHANT> MERCHANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MERCHANT> MERCHANT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MERCHANT_CARDTYPE_PERMISSION> MERCHANT_CARDTYPE_PERMISSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEMPLATE> USERTEMPLATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_ORGANIZATION_MAP> USER_ORGANIZATION_MAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTEMPLATE> USERTEMPLATE1 { get; set; }
    }
}
